name: earthquakes
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - appdirs=1.4.4
  - appnope=0.1.2
  - argh=0.26.2
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=21.2.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - black=21.7b0
  - blas=2.111
  - blas-devel=3.9.0
  - bleach=4.0.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.2
  - ca-certificates=2022.4.26
  - cairo=1.16.0
  - captum=0.5.0
  - cartopy=0.18.0
  - certifi=2022.5.18.1
  - cffi=1.14.6
  - cftime=1.5.0
  - chardet=4.0.0
  - charset-normalizer=2.0.0
  - click=8.0.1
  - colorama=0.4.4
  - configparser=5.0.2
  - cryptography=3.4.7
  - curl=7.78.0
  - cycler=0.10.0
  - dataclasses=0.8
  - dbus=1.13.6
  - debugpy=1.4.1
  - decorator=5.0.9
  - defusedxml=0.7.1
  - docker-pycreds=0.4.0
  - entrypoints=0.3
  - expat=2.4.1
  - ffmpeg=4.3.2
  - fontconfig=2.13.96
  - freetype=2.10.4
  - geos=3.9.1
  - gettext=0.19.8.1
  - gitdb=4.0.7
  - gitpython=3.1.18
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - gql=0.1.0
  - graphite2=1.3.13
  - graphql-core=3.1.6
  - harfbuzz=2.9.1
  - hdf4=4.2.15
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.1
  - imbalanced-learn=0.8.1
  - importlib-metadata=4.6.4
  - ipykernel=6.2.0
  - ipynb-py-convert=0.4.6
  - ipython=7.26.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - jasper=1.900.1
  - jbig=2.1
  - jedi=0.18.0
  - jinja2=3.0.1
  - joblib=1.1.0
  - jpeg=9d
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.12
  - jupyter_console=6.4.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - lerc=2.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.78.0
  - libcxx=12.0.1
  - libdeflate=1.7
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libglib=2.68.4
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnetcdf=4.8.0
  - libnghttp2=1.43.0
  - libopencv=4.5.1
  - libpng=1.6.37
  - libpq=13.3
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.3.0
  - libuv=1.42.0
  - libwebp-base=1.2.1
  - libxml2=2.9.12
  - libzip=1.8.0
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-devel=2021.3.0
  - mkl-include=2021.3.0
  - mypy_extensions=0.4.3
  - mysql-common=8.0.25
  - mysql-libs=8.0.25
  - nbclient=0.5.4
  - nbconvert=6.1.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - netcdf4=1.5.6
  - nettle=3.6
  - ninja=1.10.2
  - notebook=6.4.3
  - nspr=4.30
  - nss=3.69
  - numpy=1.21.2
  - nvidia-ml=7.352.0
  - olefile=0.46
  - opencv=4.5.1
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1o
  - packaging=21.0
  - pandas=1.3.2
  - pandoc=2.14.1
  - pandocfilters=1.4.2
  - parso=0.8.2
  - pathlib=1.0.1
  - pathspec=0.9.0
  - pathtools=0.1.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.3.1
  - pip=21.2.4
  - pixman=0.40.0
  - plotly=4.14.3
  - proj=7.2.0
  - prometheus_client=0.11.0
  - promise=2.3
  - prompt-toolkit=3.0.19
  - prompt_toolkit=3.0.19
  - protobuf=3.17.2
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - py-opencv=4.5.1
  - pycparser=2.20
  - pygments=2.10.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqt-impl=5.12.3
  - pyqt5-sip=4.19.18
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.9.6
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytorch=1.8.1
  - pytz=2021.1
  - pyyaml=5.4.1
  - pyzmq=22.2.1
  - qt=5.12.9
  - qtconsole=5.1.1
  - qtpy=1.10.0
  - readline=8.1
  - regex=2021.8.21
  - requests=2.26.0
  - retrying=1.3.3
  - scikit-learn=1.0.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - sentry-sdk=1.3.1
  - setuptools=57.4.0
  - shapely=1.7.1
  - shortuuid=1.0.1
  - six=1.16.0
  - smmap=3.0.5
  - sqlite=3.36.0
  - subprocess32=3.5.4
  - tbb=2021.3.0
  - terminado=0.11.1
  - testpath=0.5.0
  - threadpoolctl=3.0.0
  - tk=8.6.11
  - tomli=1.2.1
  - tornado=6.1
  - tqdm=4.62.2
  - traitlets=5.0.5
  - typed-ast=1.4.3
  - typing_extensions=3.10.0.0
  - tzdata=2021a
  - urllib3=1.26.6
  - wandb=0.11.2
  - watchdog=0.10.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - x264=1!161.3030
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.5.0
  - zlib=1.2.11
  - zstd=1.5.0
